using System;

namespace Euler_collection.Problems
{
    /* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
     * the first 10 terms will be:
     * 
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     *
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
     * even-valued terms.
     */
    
    public class P002 : ProblemBase
    {
        protected override void Run()
        {
            var a = 0;
            var b = 1;
            var result = 0;

            for (var i = 2; i < int.MaxValue; i++)
            {
                var temp = a + b;
                a = b;
                b = temp;
                if (temp > 4000000)
                    break;
                if (temp % 2 == 0)
                {
                    result += temp;
                }
            }
            
            Console.WriteLine("Result: {0}", result);
        }
    }
}